name: Build precompiled NIFs

on:
  push:
    branches:
      - main
    paths:
      - "native/**"
      - ".github/workflows/release.yml"
    tags:
      - "v*"
  pull_request:
    paths:
      - ".github/workflows/release.yml"
  workflow_dispatch:

jobs:
  build_release:
    name: NIF ${{ matrix.nif }} - ${{ matrix.job.target }} (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}

    permissions:
      contents: write
      id-token: write
      attestations: write

    strategy:
      fail-fast: false
      matrix:
        nif: ["2.16"]
        job:
          - { target: aarch64-apple-darwin, os: macos-15 }
          - { target: x86_64-apple-darwin, os: macos-15 }
          - { target: aarch64-unknown-linux-gnu, os: ubuntu-22.04, use-cross: true }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-22.04 }
          - { target: x86_64-pc-windows-msvc, os: windows-2025 }

    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        shell: bash
        run: |
          echo "PROJECT_VERSION=$(sed -n 's/^  @version "\(.*\)"/\1/p' mix.exs | head -n1)" >> $GITHUB_ENV

      - name: Add target
        shell: bash
        run: rustup target add ${{ matrix.job.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: native/dux
          key: precomp-${{ matrix.job.target }}-${{ matrix.nif }}

      - name: Build
        id: build
        uses: philss/rustler-precompiled-action@v1.1.4
        with:
          project-name: dux
          project-version: ${{ env.PROJECT_VERSION }}
          target: ${{ matrix.job.target }}
          nif-version: ${{ matrix.nif }}
          use-cross: ${{ matrix.job.use-cross || false }}
          cross-version: "from-source"
          project-dir: native/dux

      - name: Artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: ${{ steps.build.outputs.file-path }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.file-name }}
          path: ${{ steps.build.outputs.file-path }}

      - name: Publish to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.build.outputs.file-path }}
